---
title: "Proyecto AED: An치lisis"
output:
  html_notebook: default
  pdf_document: default
---

```{r}
datos = read.csv(file.path("/home/oscarvch03/Desktop/Proyecto_Analisis_Estadistico", "Saber11_20_1920_2.csv"), sep = ",")
datos = datos[, 2:ncol(datos)]
head(datos)
```
```{r}
# Relacion entre Variables
areas_m = as.matrix(datos[10:14])
head(areas_m)
disimilitud = as.dist(1 - cor(areas_m))
hc1.comp = hclust(disimilitud, method="complete")
plot(hc1.comp, main="Clustering Jer치rquico por Variables (Enlace Completo)", cex = 0.5, xlab = "", ylab = "")
```
```{r}
# Clustering por Areas
library("scatterplot3d")
k = 3
km = kmeans(areas_m, k, nstart = 30)
# plot(areas_m[ , 2], areas_m[ , 3], col = km$cluster+ 1)
scatterplot3d(areas_m[ , c(1, 2, 5)], pch = 1, color = km$cluster + 1, main = "Clustering con K-means para k = 3")
table(datos$COVID, km$cluster + 1)
```
```{r}
# Componentes Principales
library(PCAmixdata)
datos.mix = splitmix(datos)
datos.PCA = PCAmix(datos.mix$X.quanti, datos.mix$X.quali, ndim = 20, rename.level = T, graph = T)
cat("\n")
cat("\n")
datos.PCA$quanti
# cat("\n")
# cat("\n")
# datos.PCA$quali$contrib
```
```{r}
cuanti = datos.PCA$quanti$contrib.pct


for(i in 1:nrow(cuanti)){
    plot(1:20, cuanti[i, ], type = "b", pch = 5, lwd = 1, col = 2, xlim = c(0, 21), ylim = c(0, 50), main = "Proporciones de Varianza \n Componentes Principales", xlab = "Comp. Principal", ylab = "% de Varianza")
    par(new = T)
    cat(i, "\n")
    #Sys.sleep(2)
}
```

```{r}
# Rotacion PCA
datos.PCA.rot = PCArot(datos.PCA, 5, graph = T)
datos.PCA.rot$quanti
cat("\n")
cat("\n")
datos.PCA.rot$quali
```



```{r}
# Analisis de Factores
class.var = c(rep(1, 3), rep(2, 3), rep(3, 3), rep(4, 6), c(5))
names = c("Car_Est", "Car_Fam", "Car_Col", "Puntajes", "Covid")
datos.MFA = MFAmix(data = datos, groups = class.var, name.groups = names, rename.level = T,                      graph = T)
summary(datos.MFA)
```
```{r}
library(caret)
set.seed(42)
trainIndex = createDataPartition(datos$COVID, p = 0.75)$Resample1
areas_train = areas_m[trainIndex, ]
areas_test = areas_m[-trainIndex, ]

## Discriminante Lineal
library(MASS)
datos.LDA = lda(areas_train, datos$COVID[trainIndex])
datos.LDA
# Calcular error de clasificacion
pred_clas1 = predict(datos.LDA, areas_test)$class
epsilon1 = 1 - sum(pred_clas1 == datos$COVID) / nrow(datos) 
epsilon1
table(datos$COVID[-trainIndex], pred_clas1)
scatterplot3d(areas_test[ , c(1, 2, 5)], pch = 1, color = c(pred_clas1), main = "Clasificaci칩n LDA tomando la variable COVID")
```
```{r}
## Discriminante Cuadratico
datos.QDA = qda(areas_train, datos$COVID[trainIndex])
datos.QDA
# Calcular error de clasificacion
pred_clas2 = predict(datos.QDA, areas_test)$class
epsilon2 = 1 - sum(pred_clas2 == datos$COVID) / nrow(datos) 
epsilon2
table(datos$COVID[-trainIndex], pred_clas2)
scatterplot3d(areas_test[ , c(1, 2, 5)], pch = 1, color = c(pred_clas2), main = "Clasificaci칩n QDA tomando la variable COVID")
```
```{r}
datos.MANOVA = manova(cbind(PUNT_LECTURA_CRITICA, PUNT_MATEMATICAS, PUNT_C_NATURALES, PUNT_SOCIALES_CIUDADANAS, PUNT_INGLES) ~ COVID, data = datos)
datos.MANOVA
fit = summary(datos.MANOVA, test = "Wilks", multivariate = T)
fit
```

